#!/usr/bin/env python3
import requests
import sys
import os
import webbrowser

INVOKE_URL = "https://thor7h42bf.execute-api.us-east-2.amazonaws.com/prod"
CLIENT_ID = "2567d513d77e46a4ab11701cdf4aa447"

def plan():
  if 'SPOTIFY_TOKEN' in os.environ:
    payload = {"token": os.environ["SPOTIFY_TOKEN"]}
    r = requests.post(f"{INVOKE_URL}/plan", data=payload)
    print(r)
  else:
    endpoint = "https://accounts.spotify.com/authorize"
    scope=[
        "user-read-email",
        "playlist-read-private",
        "playlist-modify-public",
        "playlist-modify-private"
    ]
    url = "{}?client_id={}&response_type=code&redirect_uri={}&scope={}".format(
        endpoint,
        CLIENT_ID,
        f"{INVOKE_URL}/plan",
        " ".join(scope)
    )
    webbrowser.open(url)

if __name__ == "__main__":
  command = sys.argv[1]
  if command == "plan":
    plan()
